/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author kevin
 */
public class FinancialAnalyzerGUI extends javax.swing.JFrame {

    /**
     * Creates new form FinancialAnalyzerGUI
     */
    public FinancialAnalyzerGUI() {
        initComponents();
        loanPaymentRadio.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtons = new javax.swing.ButtonGroup();
        loanPaymentRadio = new javax.swing.JRadioButton();
        investmentValueRadio = new javax.swing.JRadioButton();
        titleCalculator = new javax.swing.JLabel();
<<<<<<< HEAD
        PurchaseAmt = new javax.swing.JLabel();
=======
        textLabel1 = new javax.swing.JLabel();
>>>>>>> origin/master
        purchaseAmountText = new javax.swing.JTextField();
        textLabel2 = new javax.swing.JCheckBox();
        downPaymentText = new javax.swing.JTextField();
        textLabel3 = new javax.swing.JLabel();
        loanAmountText = new javax.swing.JTextField();
        aprTextLabel = new javax.swing.JLabel();
        aprText = new javax.swing.JTextField();
        compundingTextLabel = new javax.swing.JLabel();
        compoundingComboBox = new javax.swing.JComboBox<>();
<<<<<<< HEAD
        loanDuration = new javax.swing.JLabel();
=======
        textLabel6 = new javax.swing.JLabel();
>>>>>>> origin/master
        loanDurationText = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        summaryReportButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
<<<<<<< HEAD
        annualPayment = new javax.swing.JLabel();
        annuallyPaymentText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financial Analyzer");
        setPreferredSize(new java.awt.Dimension(359, 1000));

        radioButtons.add(loanPaymentRadio);
=======
        textLabel7 = new javax.swing.JLabel();
        monthlyPaymentText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financial Analyzer");

        radioButtons.add(loanPaymentRadio);
        loanPaymentRadio.setSelected(true);
>>>>>>> origin/master
        loanPaymentRadio.setText("Loan Payment ");
        loanPaymentRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanPaymentRadioActionPerformed(evt);
            }
        });

        radioButtons.add(investmentValueRadio);
        investmentValueRadio.setText("Investment Value");
        investmentValueRadio.setActionCommand("Investment Value ");
        investmentValueRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investmentValueRadioActionPerformed(evt);
            }
        });

        titleCalculator.setText("Loan Payment Calculator");

<<<<<<< HEAD
        PurchaseAmt.setText("Purchase Amount ");

        purchaseAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseAmountTextActionPerformed(evt);
            }
        });

        downPayment.setText("Down Payment ");
        downPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downPaymentActionPerformed(evt);
            }
        });

        downPaymentText.setText("0");
        downPaymentText.setEnabled(false);
        downPaymentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downPaymentTextActionPerformed(evt);
            }
        });
=======
        textLabel1.setText("Purchase Amount ");

        textLabel2.setText("Down Payment ");
>>>>>>> origin/master

        textLabel3.setText("Loan Amount");

<<<<<<< HEAD
        loanAmountText.setBackground(new java.awt.Color(0, 255, 255));
        loanAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountTextActionPerformed(evt);
            }
        });

        apr.setText("APR(%)");
=======
        aprTextLabel.setText("APR(%)");
>>>>>>> origin/master

        compundingTextLabel.setText("Compounding ");

        compoundingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annually", "Semiannual", "Quarterly", "Monthly", "Weekly" }));
        compoundingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compoundingComboBoxActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        loanDuration.setText("Loan Duration (years) ");
=======
        textLabel6.setText("Loan Duration (years) ");
>>>>>>> origin/master

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonClick(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonClick(evt);
            }
        });

        summaryReportButton.setText("Summary Report");
        summaryReportButton.setEnabled(false);
        summaryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryReportButtonClick(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionClickPerformed(evt);
            }
        });

<<<<<<< HEAD
        annualPayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        annualPayment.setText("Annual Payment");
=======
        textLabel7.setText("Monthly Payment");
>>>>>>> origin/master

        annuallyPaymentText.setBackground(new java.awt.Color(0, 255, 255));
        annuallyPaymentText.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(loanPaymentRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(investmentValueRadio)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(summaryReportButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(annualPayment)
                                .addGap(107, 107, 107)
                                .addComponent(annuallyPaymentText))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PurchaseAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(downPaymentText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(loanAmountText)
                                    .addComponent(purchaseAmountText)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loanDuration)
                                    .addComponent(downPayment)
                                    .addComponent(loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apr, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Compounding, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(loanDurationText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(compoundingComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(aprText))))))))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(titleCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(titleCalculator))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textLabel7)))
                        .addGap(8, 8, 8)
                        .addComponent(monthlyPaymentText))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calculateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(summaryReportButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(loanPaymentRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(investmentValueRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aprTextLabel)
                            .addComponent(textLabel1)
                            .addComponent(textLabel2)
                            .addComponent(textLabel3))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(downPaymentText)
                            .addComponent(purchaseAmountText)
                            .addComponent(loanAmountText)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compundingTextLabel)
                            .addComponent(textLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aprText)
                            .addComponent(compoundingComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loanDurationText))))
                .addGap(59, 59, 59))
>>>>>>> origin/master
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanPaymentRadio)
                    .addComponent(investmentValueRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleCalculator)
<<<<<<< HEAD
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PurchaseAmt)
=======
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel1)
>>>>>>> origin/master
                    .addComponent(purchaseAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel2)
                    .addComponent(downPaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel3)
                    .addComponent(loanAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aprTextLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compoundingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compundingTextLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
<<<<<<< HEAD
                    .addComponent(loanDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanDurationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualPayment)
                    .addComponent(annuallyPaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                    .addComponent(textLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanDurationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel7)
                    .addComponent(monthlyPaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
>>>>>>> origin/master
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(summaryReportButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(exitButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        loanPaymentRadio.getAccessibleContext().setAccessibleName("loanPaymentRadio");
        investmentValueRadio.getAccessibleContext().setAccessibleName("investmentValueRadio");
        titleCalculator.getAccessibleContext().setAccessibleName("titleCalculator");
        loanDuration.getAccessibleContext().setAccessibleName("Loan Duration (years) ");

        setSize(new java.awt.Dimension(388, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonClick
        summaryReportButton.setEnabled(true);
        //p 98, 209, if statements for compounding
    }//GEN-LAST:event_calculateButtonClick

    private void summaryReportButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryReportButtonClick
        

    }//GEN-LAST:event_summaryReportButtonClick

    private void clearButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonClick
        
<<<<<<< HEAD
        radioButtons.clearSelection(); //Clears selected radio button
        purchaseAmountText.setText("");
        downPaymentText.setText("");
        downPayment.setSelected(false); //Clears the check box
        downPaymentText.setEnabled(false);
=======
      
        purchaseAmountText.setText("");
        downPaymentText.setText("");
        textLabel2.setSelected(false); //Clears the check box
>>>>>>> origin/master
        loanAmountText.setText("");
        aprText.setText("");        
        compoundingComboBox.setSelectedIndex(0); //Resets compounding option
        loanDurationText.setText("");
        annuallyPaymentText.setText("");
        summaryReportButton.setEnabled(false);
        

    }//GEN-LAST:event_clearButtonClick

    private void exitButtonActionClickPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionClickPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionClickPerformed
    
    private void investmentValueRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investmentValueRadioActionPerformed
<<<<<<< HEAD
        if (investmentValueRadio.isSelected());
        investmentValueRadio.setSelected(true);
        
        PurchaseAmt.setText("Monthly Investment");
        downPayment.setText("Initial Investment");
        loanDuration.setText("Investment Period (years)");
        annualPayment.setText("Future Value");
        loanAmount.setText("");
        loanAmountText.setEnabled(false);
      
        
    }//GEN-LAST:event_investmentValueRadioActionPerformed

    private void loanPaymentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanPaymentRadioActionPerformed

        //code for which radio button is selected
        if (loanPaymentRadio.isSelected()) {
            loanPaymentRadio.setSelected(true);
        }
        downPayment.setText("Down Payment");
        

    }//GEN-LAST:event_loanPaymentRadioActionPerformed

    private void purchaseAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseAmountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseAmountTextActionPerformed

    private void compoundingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compoundingComboBoxActionPerformed
        String compoundingText = (String) compoundingComboBox.getSelectedItem();
        if (compoundingText.equals("Annually")) {
            annualPayment.setText("Annual Payment");
        } else if (compoundingText.equals("Semiannual")) {
            annualPayment.setText("Semiannual Payment");
        } else if (compoundingText.equals("Monthly")) {
            annualPayment.setText("Monthly Payment");
        } else if (compoundingText.equals("Weekly")) {
            annualPayment.setText("Weekly Payment");
        } else if (compoundingText.equals("Quarterly")) {
            annualPayment.setText("Quarterly Payment");
        }
        

    }//GEN-LAST:event_compoundingComboBoxActionPerformed

    private void downPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downPaymentActionPerformed
        if (downPayment.isSelected()) {
            downPaymentText.setEnabled(true);
        } else {
            downPaymentText.setEnabled(false);
        }
    }//GEN-LAST:event_downPaymentActionPerformed

    private void downPaymentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downPaymentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downPaymentTextActionPerformed

    private void loanAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountTextActionPerformed
        
    }//GEN-LAST:event_loanAmountTextActionPerformed
=======
        // TODO add your handling code here:
        // when investment radio button is clicked, change labels 
       textLabel1.setText("Monthly Investment");
       textLabel2.setText("Initial Investment"); 
       textLabel3.setText("");
       textLabel6.setText("Investment Period (years"); 
       textLabel7.setText("Future Value");
       
    }//GEN-LAST:event_investmentValueRadioActionPerformed

    private void loanPaymentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanPaymentRadioActionPerformed
        
        textLabel1.setText("Purchase Amount");
        textLabel2.setText("Down Payment");
        textLabel3.setText("Loan Payment");
        textLabel6.setText("Loan Duration (years)");
        textLabel7.setText("Monthly Payment");
            
                
    }//GEN-LAST:event_loanPaymentRadioActionPerformed

    private void compoundingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compoundingComboBoxActionPerformed
        /*
        CompoundingOption oldValue = compoundingOption;
        compoundingOption = getSelectedCompounding();
        compoundingText = (String) compoundingCBox.getSelectedItem();
        
        if(loanRadioButton.isSelected()){
            resultLabel.setText(compoundingText + "Payment");
        }else{
            requiredCashFlowLabel.setText(compoundingText + "Investment");
        }
        if(compoundingOption.getPeriodsPerYear() != oldValue.getPeriodsPerYear()){
            resultTextField.setText("");
            reportButton.setEnabled(false);
        }
        */
    }//GEN-LAST:event_compoundingComboBoxActionPerformed
>>>>>>> origin/master

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //this code center the GUI on the screen when running 
                FinancialAnalyzerGUI frame = new FinancialAnalyzerGUI();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JLabel Compounding;
    private javax.swing.JLabel PurchaseAmt;
    private javax.swing.JLabel annualPayment;
    private javax.swing.JTextField annuallyPaymentText;
    private javax.swing.JLabel apr;
    private javax.swing.JTextField aprText;
=======
    private javax.swing.JTextField aprText;
    private javax.swing.JLabel aprTextLabel;
>>>>>>> origin/master
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> compoundingComboBox;
    private javax.swing.JLabel compundingTextLabel;
    private javax.swing.JTextField downPaymentText;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton investmentValueRadio;
<<<<<<< HEAD
    private javax.swing.JLabel loanAmount;
=======
>>>>>>> origin/master
    private javax.swing.JTextField loanAmountText;
    private javax.swing.JLabel loanDuration;
    private javax.swing.JTextField loanDurationText;
    private javax.swing.JRadioButton loanPaymentRadio;
<<<<<<< HEAD
=======
    private javax.swing.JTextField monthlyPaymentText;
>>>>>>> origin/master
    private javax.swing.JTextField purchaseAmountText;
    private javax.swing.ButtonGroup radioButtons;
    private javax.swing.JButton summaryReportButton;
    private javax.swing.JLabel textLabel1;
    private javax.swing.JCheckBox textLabel2;
    private javax.swing.JLabel textLabel3;
    private javax.swing.JLabel textLabel6;
    private javax.swing.JLabel textLabel7;
    private javax.swing.JLabel titleCalculator;
    // End of variables declaration//GEN-END:variables
}
