/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import javax.swing.Icon; 
import finance.Investment;
import finance.LoanPayment; 
import finance.TVMEngine; 
import finance.ReportGenerator; 
import finance.enums.CompoundingOption;


/**
 *
 * @author kevin
 */
public class FinancialAnalyzerGUI extends javax.swing.JFrame {
    
    private TVMEngine engine; 
    private ReportGenerator report; 
    
    
    public FinancialAnalyzerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtons = new javax.swing.ButtonGroup();
        loanPaymentRadio = new javax.swing.JRadioButton();
        investmentValueRadio = new javax.swing.JRadioButton();
        titleCalculator = new javax.swing.JLabel();
        textLabel1 = new javax.swing.JLabel();
        textField1 = new javax.swing.JTextField();
        textLabel2 = new javax.swing.JCheckBox();
        textField2 = new javax.swing.JTextField();
        textLabel3 = new javax.swing.JLabel();
        textField3 = new javax.swing.JTextField();
        aprTextLabel = new javax.swing.JLabel();
        aprTextField = new javax.swing.JTextField();
        compundingTextLabel = new javax.swing.JLabel();
        compoundingComboBox = new javax.swing.JComboBox<>();
        textLabel6 = new javax.swing.JLabel();
        textField6 = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        summaryReportButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        textLabel7 = new javax.swing.JLabel();
        textField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financial Analyzer");

        radioButtons.add(loanPaymentRadio);
        loanPaymentRadio.setSelected(true);
        loanPaymentRadio.setText("Loan Payment ");
        loanPaymentRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanPaymentRadioActionPerformed(evt);
            }
        });

        radioButtons.add(investmentValueRadio);
        investmentValueRadio.setText("Investment Value");
        investmentValueRadio.setActionCommand("Investment Value ");
        investmentValueRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investmentValueRadioActionPerformed(evt);
            }
        });

        titleCalculator.setText("Loan Payment Calculator");

        textLabel1.setText("Purchase Amount ");

        textField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textField1.setToolTipText("");
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField1KeyReleased(evt);
            }
        });

        textLabel2.setText("Down Payment ");
        textLabel2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                textLabel2StateChanged(evt);
            }
        });

        textField2.setEnabled(false);
        textField2.setText("0");
        textField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textLabel3.setText("Loan Amount");

        textField3.setEditable(false);
        textField3.setBackground(java.awt.Color.cyan);
        textField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        aprTextLabel.setText("APR(%)");

        aprTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        compundingTextLabel.setText("Compounding ");

        compoundingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annual", "Semiannual", "Quarterly", "Monthly", "Weekly" }));
        compoundingComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compoundingComboBoxMouseClicked(evt);
            }
        });
        compoundingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compoundingComboBoxActionPerformed(evt);
            }
        });

        textLabel6.setText("Loan Duration (years) ");

        textField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonClick(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonClick(evt);
            }
        });

        summaryReportButton.setText("Summary Report");
        summaryReportButton.setEnabled(false);
        summaryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryReportButtonClick(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionClick(evt);
            }
        });

        textLabel7.setText("Annual Payment");

        textField7.setEditable(false);
        textField7.setBackground(java.awt.Color.cyan);
        textField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textField7.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(titleCalculator)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calculateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(summaryReportButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(loanPaymentRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(investmentValueRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aprTextLabel)
                            .addComponent(textLabel1)
                            .addComponent(textLabel2)
                            .addComponent(textLabel3))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField2)
                            .addComponent(textField1)
                            .addComponent(textField3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compundingTextLabel)
                            .addComponent(textLabel6)
                            .addComponent(textLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField7)
                            .addComponent(compoundingComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 113, Short.MAX_VALUE)
                            .addComponent(aprTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanPaymentRadio)
                    .addComponent(investmentValueRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleCalculator)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel1)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel2)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel3)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aprTextLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compoundingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compundingTextLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel7)
                    .addComponent(textField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(summaryReportButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(exitButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        loanPaymentRadio.getAccessibleContext().setAccessibleName("loanPaymentRadio");
        investmentValueRadio.getAccessibleContext().setAccessibleName("investmentValueRadio");
        titleCalculator.getAccessibleContext().setAccessibleName("titleCalculator");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonClick

            calculation();
    }//GEN-LAST:event_calculateButtonClick

    private void calculation(){
        double purchaseAmount; 
        double downPayment; 
        double apr; 
        int compounding; 
        double loanDuration; 

        purchaseAmount = Double.parseDouble(textField1.getText()); 
        downPayment = Double.parseDouble(textField2.getText());  
        apr = Double.parseDouble(aprTextField.getText()); 
        compounding = compoundingComboBox.getSelectedIndex(); 
        loanDuration = Double.parseDouble(textField6.getText()); 
        
        if (loanPaymentRadio.isSelected()){
            LoanPayment newLoanPayment = new LoanPayment(purchaseAmount, downPayment, apr, comboBoxIndex(), loanDuration); 
            engine = newLoanPayment; 
            report = newLoanPayment; 
        } else {
            Investment newInvestment = new Investment(downPayment, purchaseAmount, apr, comboBoxIndex(), loanDuration); 
            engine = newInvestment; 
            report = newInvestment; 
        }
        textField7.setText(engine.getValue());
        summaryReportButton.setEnabled(true);
    }
    
    private CompoundingOption comboBoxIndex(){
       int index = compoundingComboBox.getSelectedIndex(); 
       CompoundingOption compounding; 
       
       if(index == 0){
           compounding = CompoundingOption.ANNUAL; 
       } else if (index == 1){
           compounding = CompoundingOption.SEMIANNUAL; 
       } else if (index == 2){
           compounding = CompoundingOption.QUARTERLY; 
       } else if (index == 3){
           compounding =  CompoundingOption.MONTHLY; 
       } else {
           compounding = CompoundingOption.WEEKLY; 
       }
        return compounding; 
    }
    
  
    private void summaryReportButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryReportButtonClick
        // TODO add your handling code here:
        
        if(loanPaymentRadio.isSelected()){
           
        }else{
            
        }
    }//GEN-LAST:event_summaryReportButtonClick

    private void clearButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonClick
       
        //clears all fields
        textField1.setText("");
        textField2.setText("");
        textLabel2.setSelected(false); //Clears the check box
        textField3.setText("");
        aprTextField.setText(""); 
        compoundingComboBox.setSelectedIndex(0); //Resets compounding option
        textField6.setText("");
        textField7.setText("");
        textField2.setText("0");
        
        

    }//GEN-LAST:event_clearButtonClick

    private void exitButtonActionClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionClick
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionClick

    private void investmentValueRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investmentValueRadioActionPerformed
        
       // when investment radio button is clicked, change labels 
       textLabel1.setText("Monthly Investment");
       textLabel2.setText("Initial Investment"); 
       textLabel3.setText("");
       textLabel6.setText("Investment Period (years)"); 
       textLabel7.setText("Future Value");
       
       //calls clear button function when radio button is selected
       clearButtonClick(null);
       
       //disables loan amount text and box
       textField3.setEnabled(false);
       if(!textLabel2.isSelected()){
           textField2.setEnabled(false);
       }
       
    }//GEN-LAST:event_investmentValueRadioActionPerformed

    private void loanPaymentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanPaymentRadioActionPerformed
        
        // when loan payment radio button is clicked, change labels
        textLabel1.setText("Purchase Amount");
        textLabel2.setText("Down Payment");
        textLabel3.setText("Loan Payment");
        textLabel6.setText("Loan Duration (years)");
        textLabel7.setText("Monthly Payment");
        textLabel2.setEnabled(true);
        textField3.setEnabled(true);
        
        //calls clear buton function when radio button is selected
        clearButtonClick(null);
            
                
    }//GEN-LAST:event_loanPaymentRadioActionPerformed

    private void compoundingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compoundingComboBoxActionPerformed

        String selection = (String) compoundingComboBox.getSelectedItem();
        
        //Payment/Investment frequency label changes 
        if(loanPaymentRadio.isSelected()){
            textLabel7.setText(selection + " Payment");
        }else{
            textLabel1.setText(selection + " Investment");
        }
        //
        if(lastCombo != selection){
            textField7.setText("");
            summaryReportButton.setEnabled(false);
        }
        
//        if(compoundingOption.getPeriodsPerYear() != oldValue.getPeriodsPerYear()){
//            resultTextField.setText("");
//            reportButton.setEnabled(false);
//        }
        
//        CompoundingOption oldValue = compoundingOption;
//        String compoundingOption = getSelectedCompounding();
//        compoundingText = (String) compoundingCBox.getSelectedItem();
//        
//        if(loanRadioButton.isSelected()){
//            resultLabel.setText(compoundingText + "Payment");
//        }else{
//            requiredCashFlowLabel.setText(compoundingText + "Investment");
//        }
//        if(compoundingOption.getPeriodsPerYear() != oldValue.getPeriodsPerYear()){
//            resultTextField.setText("");
//            reportButton.setEnabled(false);
//        }
          
    }//GEN-LAST:event_compoundingComboBoxActionPerformed

    private void textLabel2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_textLabel2StateChanged
        
        // Greys out and adds 0 if unchecked and the opposite if checked
        if(textLabel2.isSelected()){
            textField2.setEnabled(true);
            textField2.setText("");
        }else{
            textField2.setEnabled(false);
            textField2.setText("0");
        }
    }//GEN-LAST:event_textLabel2StateChanged

    private void textField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyReleased
        textField3.setText(textField1.getText());
    }//GEN-LAST:event_textField1KeyReleased

    private String lastCombo;
    
    private void compoundingComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compoundingComboBoxMouseClicked
        //
        lastCombo = (String) compoundingComboBox.getSelectedItem();
    }//GEN-LAST:event_compoundingComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancialAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //this code center the GUI on the screen when running 
                FinancialAnalyzerGUI frame = new FinancialAnalyzerGUI();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aprTextField;
    private javax.swing.JLabel aprTextLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> compoundingComboBox;
    private javax.swing.JLabel compundingTextLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton investmentValueRadio;
    private javax.swing.JRadioButton loanPaymentRadio;
    private javax.swing.ButtonGroup radioButtons;
    private javax.swing.JButton summaryReportButton;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextField textField3;
    private javax.swing.JTextField textField6;
    private javax.swing.JTextField textField7;
    private javax.swing.JLabel textLabel1;
    private javax.swing.JCheckBox textLabel2;
    private javax.swing.JLabel textLabel3;
    private javax.swing.JLabel textLabel6;
    private javax.swing.JLabel textLabel7;
    private javax.swing.JLabel titleCalculator;
    // End of variables declaration//GEN-END:variables
}
